### ISSUE TITLE
Regarding robot configuration issues.

### ISSUE THREAD

**Issue by Xu-robot-learning** [ir-lab/irl_control#5]
When I execute force_test.py file, the problem appears on line 79:
if self.name == "ur5right" or self.name == "ur5left":
            self.sim.qpos[self.joint_ids] = np.copy(self.start_angles)
rerurn the error:
shape mismatch: value array of shape (6,) could not be broadcast to indexing result of shape (7,).
Can you tell me why and how to modify code？Thanks！

**Comment by kavinwkp** [comment]
You can add a dimension to `start_angles` in `default_xyz.yaml`, e.g. `start_angles: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]` for `ur5right` and `start_angles: [0.126, -0.942, -1.88, -4.15, -4.78, 0.0, 0.0]` for `ur5left`.

**Comment by HaMengder** [comment]
Adding a dimension can avoid errors, but UR5 has a pose problem and should put the added dimension in the first place. eg `start_angles: [0.0, 0.126, -0.942, -1.88, -4.15, -4.78, 0.0]`

**Comment by mdrolet01** [comment]
Hello, sorry for the late reply here. From what I recall, there may be a yaml mismatch with the device.py file. If you are still interested, you can find a newer/working version of irl_control here: https://github.com/ir-lab/bimanual-imitation, which shouldn't have this problem.
