### ISSUE TITLE
running the example FileNotFoundError appeared

### ISSUE THREAD

**Issue by flilqhu** [ir-lab/irl_control#6]
When I install the irl_control but when I run the example, it shows me the following error:
`Traceback (most recent call last):
  File "/home/lif/irl_control/build/lib/irl_control/examples/gain_test.py", line 180, in <module>
    demo = GainTest(robot_config_file="default_xyz.yaml", scene_file="gain_test_scene.xml")
  File "/home/lif/irl_control/build/lib/irl_control/examples/gain_test.py", line 22, in __init__
    super().__init__(robot_config_file, scene_file)
  File "/usr/local/lib/python3.10/dist-packages/irl_control-1.0.0-py3.10.egg/irl_control/mujoco_app.py", line 15, in __init__
    with open(robot_config_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/irl_control-1.0.0-py3.10.egg/irl_control/robot_configs/default_xyz.yaml'
`
Please tell me how to avoid this error, thank you.

**Comment by lxk-221** [comment]
It may not be a good solution, but it can be a makeshift.
you can edit the variable "main_dir" at mujoco_app.py line 13 and insertion_task.py line 137. change the variable from os.path.dirname(irl_control.__file__) to the exact path where you can find yaml files.

**Comment by mdrolet01** [comment]
Hello, sorry for the late reply here, but I will close this issue as it looks like this was due to not installing the package with pip properly. If you install it as an editable installation (using "pip install -e .") it should avoid this problem.
